"""Update BookShelf to use ShelfEnum to simplify relationships

Revision ID: 05a2522fc82d
Revises: 6486385e03ac
Create Date: 2024-09-13 19:36:02.920023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a2522fc82d'
down_revision = '6486385e03ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf', sa.Enum('NONE', 'WANT_TO_READ', 'CURRENTLY_READING', 'READ', name='shelfenum'), nullable=True))
        batch_op.drop_constraint('book_shelves_shelfID_fkey', type_='foreignkey')
        batch_op.drop_column('shelfID')

    op.drop_table('shelves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelfID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('book_shelves_shelfID_fkey', 'shelves', ['shelfID'], ['shelfID'])
        batch_op.drop_column('shelf')

    op.create_table('shelves',
    sa.Column('shelfID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shelf_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('userID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], name='shelves_userID_fkey'),
    sa.PrimaryKeyConstraint('shelfID', name='shelves_pkey')
    )
    # ### end Alembic commands ###
