"""Update BookShelf to have shelf property not nullable

Revision ID: 1327bdaa7e0d
Revises: 05a2522fc82d
Create Date: 2024-09-13 19:54:42.805105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1327bdaa7e0d'
down_revision = '05a2522fc82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE book_shelves SET shelf = 'WANT_TO_READ'")

    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.alter_column('shelf',
               existing_type=postgresql.ENUM('WANT_TO_READ', 'CURRENTLY_READING', 'READ', name='shelfenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.alter_column('shelf',
               existing_type=postgresql.ENUM('WANT_TO_READ', 'CURRENTLY_READING', 'READ', name='shelfenum'),
               nullable=True)

    op.execute("UPDATE book_shelves SET shelf = NULL")
    # ### end Alembic commands ###
