"""Add BookShelf id and UniqueConstraint isbn13 to userID

Revision ID: 1cd4dcb367cb
Revises: 1327bdaa7e0d
Create Date: 2024-09-14 09:56:30.223921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd4dcb367cb'
down_revision = '1327bdaa7e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.create_unique_constraint('_isbn13_user_uc', ['isbn13', 'userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.drop_constraint('_isbn13_user_uc', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
