"""Add curated lists and picks tables

Revision ID: 5a60dde3c420
Revises: 525c7d8f2035
Create Date: 2024-11-19 19:59:07.816303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a60dde3c420'
down_revision = '525c7d8f2035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('isbn_13', sa.String(length=13), nullable=True),
    sa.Column('isbn_10', sa.String(length=10), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['curated_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'position', name='uq_curated_list_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curated_picks')
    # ### end Alembic commands ###
