"""Update BookShelf to include userID

Revision ID: 6486385e03ac
Revises: bff847282834
Create Date: 2024-09-13 11:00:21.624814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6486385e03ac'
down_revision = 'bff847282834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['userID'], ['userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userID')

    # ### end Alembic commands ###
