"""Rename bookId to isbn13, drop rating, add image and shelf columns

Revision ID: 89f43ef6b8be
Revises: 
Create Date: 2024-09-09 12:26:28.617651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f43ef6b8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        op.alter_column('books', 'bookId', new_column_name='isbn13')
        op.create_unique_constraint('uq_books_isbn13', 'books', ['isbn13'])
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('shelf', sa.String(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bookId', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('shelf')
        batch_op.drop_column('image')
        batch_op.drop_column('isbn13')

    # ### end Alembic commands ###
