"""Initial clean deployment migration

Revision ID: 97921b0c7211
Revises: 
Create Date: 2025-05-30 11:47:23.127471

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '97921b0c7211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('isbn13', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('authors', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('isbn13')
                    )
    op.create_table('curated_lists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('userID', sa.String(), nullable=False),
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('userID'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('userID')
                    )
    op.create_table('book_shelves',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('isbn13', sa.String(), nullable=False),
                    sa.Column('userID', sa.String(), nullable=False),
                    sa.Column('shelf', sa.Enum('WANT_TO_READ', 'CURRENTLY_READING', 'READ', name='shelfenum'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['isbn13'], ['books.isbn13'], ),
                    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('isbn13', 'userID', name='_isbn13_user_uc')
                    )
    op.create_table('curated_picks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('list_id', sa.Integer(), nullable=False),
                    sa.Column('isbn13', sa.String(length=13), nullable=True),
                    sa.Column('isbn10', sa.String(length=10), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['list_id'], ['curated_lists.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('list_id', 'position', name='uq_curated_list_position')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curated_picks')
    op.drop_table('book_shelves')
    op.drop_table('users')
    op.drop_table('curated_lists')
    op.drop_table('books')
    # ### end Alembic commands ###
