"""Convert author to authors ARRAY of String

Revision ID: bff847282834
Revises: 1ec32f588df0
Create Date: 2024-09-10 15:45:01.492763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff847282834'
down_revision = '1ec32f588df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.ARRAY(sa.String()), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
