"""Rename pick tables and columns

Revision ID: e9ee09d4a644
Revises: 5a60dde3c420
Create Date: 2024-12-30 10:43:19.811315

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e9ee09d4a644'
down_revision = '5a60dde3c420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curated_picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn13', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('isbn10', sa.String(length=10), nullable=True))
        batch_op.drop_column('isbn_13')
        batch_op.drop_column('isbn_10')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curated_picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn_10', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isbn_13', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
        batch_op.drop_column('isbn10')
        batch_op.drop_column('isbn13')

    # ### end Alembic commands ###
